# server:
#   port: 9090

spring:
  application:
    name: SpringBootWEB

    #H2 Console COnfiguration
    h2: 
      console: 
        enabled: true
        path: /h2-console

    #DataBase Connection COnfiguration
    datasource: 
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sahil
      password: password

    #Show SQL quesries in the console
    jpa:
      show-sql: true
    
    logging:
      level:
          root: info                    # Standard logs for the whole app
          org.springframework.web: debug # Shows detailed info about incoming web requests
    
    management:
      endpoints:
          web:
          exposure:
              include: "health,info,metrics" # Exposes http://localhost:8080/actuator/health
    
    
